---
- name: include secret vars
  include_vars: secret.yml

- name: stat n
  stat:
    path: /usr/local/bin/n
  register: n

- block:
  - name: install temp node
    apt:
      name: nodejs
      update_cache: yes
  - name: install temp npm
    apt:
      name: npm
  - name: install n
    npm:
      name: n
      global: yes
  - name: install node by n
    command: n stable
  - name: remove temp node
    apt:
      name: nodejs
      state: absent
  - name: remove temp npm
    apt:
      name: npm
      state: absent
  when: not n.stat.exists

- name: install yarn
  npm:
    name: yarn
    global: yes

- name: install packages
  apt:
    name:
      - git
      - libnss-mdns
      - libavahi-compat-libdnssd-dev

- name: clone google-home-pokemon-dictionary
  git:
    repo: https://github.com/reireias/google-home-pokemon-dictionary.git
    dest: /opt/google-home-pokemon-dictionary
  register: clone

- block:
  - name: yarn install
    yarn:
      path: /opt/google-home-pokemon-dictionary
  # NOTE: https://qiita.com/hideo-works/items/06e54359bc651a928b2f
  - name: replace mdns script
    replace:
      dest: /opt/google-home-pokemon-dictionary/node_modules/mdns/lib/browser.js
      regexp: 'rst.getaddrinfo()'
      replace: 'rst.getaddrinfo({families:[4]})'
  - name: delete file glob
    find:
      paths: /tmp/
      patterns: yarn*
    register: files_to_delete
  - name: remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
  when: clone.changed

- name: set .env
  template:
    src: .env.j2
    dest: /opt/google-home-pokemon-dictionary/.env
    mode: 0644

- name: copy systemd file
  copy:
    src: pokemon-dictionary.service
    dest: /etc/systemd/system/pokemon-dictionary.service
    mode: 0644

- name: enable pokemon-dictionary.service
  systemd:
    name: pokemon-dictionary
    enabled: yes
    state: started

- name: restart pokemon-dictionary.service
  systemd:
    name: pokemon-dictionary
    state: restarted
  when: clone.changed
